### ISSUE TITLE
About seek error and results

### ISSUE THREAD

**Issue by Hpjhpjhs** [yiyuan1991/3D-Face-GCNs#29]
@FuxiCV 
Hi, thanks for your great work! There would be some errors when the model is training, but the training can still continue. First of all, the os seek function problem appears in training from time to time like below:
'''
W tensorflow/core/framework/op_kernel.cc:1389] Unknown: OSError: [Errno 22] Invalid argument
Traceback (most recent call last):

  File "C:\Users\Administrator\anaconda3\envs\ms3d-gpu\lib\site-packages\tensorflow\python\ops\script_ops.py", line 207, in __call__
    ret = func(*args)

  File "F:\3D-Face-GCNs\3D-Face-GCNs-master\base_model.py", line 833, in load_image_bin
    return utils.load_image_bin(start_idx, self.img_file, image_len, self.img_size)

  File "F:\3D-Face-GCNs\3D-Face-GCNs-master\utils.py", line 65, in load_image_bin
    img_file.seek(img_start)

OSError: [Errno 22] Invalid argument
'''
Have you any suggestions?
Besides, In addition, as the training progresses, the evaluated pictures become strange like below:
The GCN_image:
![222180_gcn_ren_clr](https://user-images.githubusercontent.com/49031501/120166801-9260c900-c22f-11eb-8c9c-e0afcbcf45d1.png)
The input_image:
![222180_input](https://user-images.githubusercontent.com/49031501/120166866-a5739900-c22f-11eb-93c0-fc2e50f04db5.png)
The PCA_image:
![222180_pca_ren_clr](https://user-images.githubusercontent.com/49031501/120166886-aad0e380-c22f-11eb-8f48-8f19925568f8.png)
Do you know why this happened?

Finally, can we ignore this error: "- x - INFO: - Error Occured in Sess Run." Maybe this happens when the gradients are None or INF.
It's appreciated If I can receive your reply.

**Comment by haoxurt** [comment]
@Hpjhpjhs Could you tell me how install `spatialsearch ` successfully and your version of python?
